Add tracking branch for coreJSON
aws/aws-iot-device-sdk-embedded-C pull request #1395
Opened 2020-11-18 18:31 UTC by aggarw13

*Description of changes:*
`git submodule update --remote -f` fails for `coreJSON` submodule as the submodule pointer update is attempted on `origin/master` instead of `origin/main`

```
╰─➤  git submodule update --init -f --remote
Submodule path 'libraries/3rdparty/CMock': checked out '9c1c6a05dc7aa41d6a2da39b9f916be373ef050e'
Submodule path 'libraries/aws/device-defender-for-aws-iot-embedded-sdk': checked out '9ba281dafdf7f48941fc7f20740716883019fcfc'
Submodule path 'libraries/aws/device-shadow-for-aws-iot-embedded-sdk': checked out 'fabbece424c03f2f90a2c5b1117bcb44cbe9257b'
Submodule path 'libraries/aws/jobs-for-aws-iot-embedded-sdk': checked out '2c6628c36cb905763037265776d0d811ec7f863d'
Submodule path 'libraries/standard/coreHTTP': checked out '0882657628eb7df12dc957f9b122601fd3054a68'
fatal: Needed a single revision
Unable to find current origin/master revision in submodule path 'libraries/standard/coreJSON'
```

This PR fixes the issue by adding a tracking branch configuration for the `coreJSON`  submodule.

By submitting this pull request, I confirm that my contribution is made under the terms of the MIT license.

2020-11-18 19:03 UTC, nateglims commented
Other repos are converted but haven't deleted their master branch yet. Should we update them all at once?

2020-11-18 19:18 UTC, sarenameas requested changes

2020-11-18 19:18 UTC, sarenameas commented on .gitmodules
> +	branch = main
Not necessary with the latest, I will put back the master branch as non-default in coreJSON so that older commits won't fail.

2020-11-18 19:27 UTC, sarenameas commented on .gitmodules
> +	branch = main
I feel like it's lame we have to do this

2020-11-18 21:28 UTC, sarenameas commented on .gitmodules
>  	url = https://github.com/aws/jobs-for-aws-iot-embedded-sdk.git
```suggestion
	url = https://github.com/aws/jobs-for-aws-iot-embedded-sdk.git
	branch = main
```

2020-11-18 22:43 UTC, nateglims submitted a review, later dismissed

2020-11-18 23:30 UTC, sarenameas submitted a review, later dismissed

2020-11-19 01:40 UTC, sarenameas submitted a review, later dismissed

2020-11-19 01:40 UTC, dan4thewin submitted a review, later dismissed

2020-11-19 01:41 UTC, sarenameas approved these changes

2020-11-19 01:42 UTC, dan4thewin approved these changes

2020-11-19 02:03 UTC, merged