Fix MISRA warnings of ota PAL file.
aws/aws-iot-device-sdk-embedded-C pull request #1435
Opened 2020-12-08 07:43 UTC by xuelix

Fix MISRA warnings of ota_pal_posix.c and ota_pal_posix.h

By submitting this pull request, I confirm that my contribution is made under the terms of the MIT license.

2020-12-08 20:27 UTC, AniruddhaKanhere requested changes

2020-12-08 21:33 UTC, xuelix commented on platform/posix/ota_pal/source/include/ota_pal_posix.h
> +OtaPalStatus_t otaPal_Abort( OtaFileContext_t * const C );
The violated rule is to have a different name from .h file.   All implementation in .c file is using C.  I'd rather change the .h file not the .c file

2020-12-08 21:36 UTC, AniruddhaKanhere commented on platform/posix/ota_pal/source/include/ota_pal_posix.h
> +OtaPalStatus_t otaPal_Abort( OtaFileContext_t * const C );
I see. Makes sense. Although a descriptive name would have been better. But, not a blocker.

2020-12-08 21:53 UTC, AniruddhaKanhere submitted a review, later dismissed

2020-12-08 22:46 UTC, cobusve commented on platform/posix/ota_pal/source/include/ota_pal_posix.h
> +OtaPalStatus_t otaPal_Abort( OtaFileContext_t * const C );
It sounds like the correct fix here is to update the name in the header file to match is it not?

2020-12-08 22:57 UTC, cobusve submitted a review, later dismissed

2020-12-08 23:51 UTC, AniruddhaKanhere approved these changes

2020-12-09 00:04 UTC, cobusve approved these changes

2020-12-09 00:09 UTC, merged