Update broken links in demo comments and documentation.
aws/aws-iot-device-sdk-embedded-C pull request #1552
Opened 2021-02-23 03:32 UTC by leegeth

*Issue #, if available:*
Github issue #1546

*Description of changes:*
Update broken links in demo comments and documentation.

By submitting this pull request, I confirm that my contribution is made under the terms of the MIT license.

2021-02-23 03:47 UTC, yourslab submitted a review, later dismissed

2021-02-23 16:00 UTC, gkwicker requested changes

2021-02-23 17:04 UTC, leegeth commented on README.md
> +Also, running the AWS IoT Device Defender, AWS IoT Jobs and AWS IoT Device Shadow library demos require the setup of a Thing resource for the device running the demo.
Thanks. Addressed it

2021-02-23 18:30 UTC, yourslab approved these changes

2021-02-24 19:06 UTC, gkwicker approved these changes

2021-02-24 19:06 UTC, merged